# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sigma-swiper.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SigmaSwiper(object):
    def setupUi(self, SigmaSwiper):
        SigmaSwiper.setObjectName("SigmaSwiper")
        SigmaSwiper.setEnabled(True)
        SigmaSwiper.resize(800, 480)
        self.id_input = QtWidgets.QLineEdit(SigmaSwiper)
        self.id_input.setGeometry(QtCore.QRect(0, 450, 711, 31))
        self.id_input.setObjectName("id_input")
        self.submit_button = QtWidgets.QPushButton(SigmaSwiper)
        self.submit_button.setGeometry(QtCore.QRect(710, 450, 91, 31))
        self.submit_button.setObjectName("submit_button")
        self.lcdNumber = QtWidgets.QLCDNumber(SigmaSwiper)
        self.lcdNumber.setGeometry(QtCore.QRect(400, 130, 391, 141))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.count_label = QtWidgets.QLabel(SigmaSwiper)
        self.count_label.setGeometry(QtCore.QRect(460, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.count_label.setFont(font)
        self.count_label.setObjectName("count_label")
        self.guest_list_label = QtWidgets.QLabel(SigmaSwiper)
        self.guest_list_label.setGeometry(QtCore.QRect(10, 290, 371, 121))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.guest_list_label.setFont(font)
        self.guest_list_label.setFrameShape(QtWidgets.QFrame.Box)
        self.guest_list_label.setObjectName("guest_list_label")
        self.guest_list_check_label = QtWidgets.QLabel(SigmaSwiper)
        self.guest_list_check_label.setGeometry(QtCore.QRect(400, 290, 391, 121))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.guest_list_check_label.setFont(font)
        self.guest_list_check_label.setFrameShape(QtWidgets.QFrame.Box)
        self.guest_list_check_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.guest_list_check_label.setText("")
        self.guest_list_check_label.setObjectName("guest_list_check_label")
        self.load_guest_list_button = QtWidgets.QPushButton(SigmaSwiper)
        self.load_guest_list_button.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.load_guest_list_button.setObjectName("load_guest_list_button")
        self.export_list_button = QtWidgets.QPushButton(SigmaSwiper)
        self.export_list_button.setGeometry(QtCore.QRect(400, 10, 391, 41))
        self.export_list_button.setObjectName("export_list_button")
        self.list_preview = QtWidgets.QListWidget(SigmaSwiper)
        self.list_preview.setGeometry(QtCore.QRect(10, 130, 371, 141))
        self.list_preview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_preview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.list_preview.setObjectName("list_preview")
        self.list_preview_label = QtWidgets.QLabel(SigmaSwiper)
        self.list_preview_label.setGeometry(QtCore.QRect(90, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.list_preview_label.setFont(font)
        self.list_preview_label.setObjectName("list_preview_label")
        self.line = QtWidgets.QFrame(SigmaSwiper)
        self.line.setGeometry(QtCore.QRect(-3, 270, 811, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(SigmaSwiper)
        self.line_2.setGeometry(QtCore.QRect(-3, 50, 801, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(SigmaSwiper)
        self.line_3.setGeometry(QtCore.QRect(379, 0, 21, 281))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(SigmaSwiper)
        QtCore.QMetaObject.connectSlotsByName(SigmaSwiper)

    def retranslateUi(self, SigmaSwiper):
        _translate = QtCore.QCoreApplication.translate
        SigmaSwiper.setWindowTitle(_translate("SigmaSwiper", "SigmaSwiper"))
        self.submit_button.setText(_translate("SigmaSwiper", "Submit"))
        self.count_label.setText(_translate("SigmaSwiper", "Number Of Guests:"))
        self.guest_list_label.setText(_translate("SigmaSwiper", "Status:"))
        self.load_guest_list_button.setText(_translate("SigmaSwiper", "Load Guest List"))
        self.export_list_button.setText(_translate("SigmaSwiper", "Save Attendance"))
        self.list_preview_label.setText(_translate("SigmaSwiper", "Recent Guests:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sigmaswiper = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(sigmaswiper)
    sigmaswiper.show()
    sys.exit(app.exec_())
