# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
class Ui_sigmaSwiper(object):
    def setupUi(self, sigmaSwiper):
        sigmaSwiper.setObjectName("sigmaSwiper")
        sigmaSwiper.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(sigmaSwiper)
        self.centralwidget.setObjectName("centralwidget")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(380, 10, 21, 271))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.guest_list_label = QtWidgets.QLabel(self.centralwidget)
        self.guest_list_label.setGeometry(QtCore.QRect(11, 300, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.guest_list_label.setFont(font)
        self.guest_list_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.guest_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.guest_list_label.setObjectName("guest_list_label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(270, 20, 111, 41))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-2, -20, 801, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-2, 270, 811, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(700, 370, 91, 31))
        self.submit_button.setObjectName("submit_button")
        self.guest_list_check_label = QtWidgets.QLabel(self.centralwidget)
        self.guest_list_check_label.setGeometry(QtCore.QRect(401, 300, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.guest_list_check_label.setFont(font)
        self.guest_list_check_label.setFrameShape(QtWidgets.QFrame.Box)
        self.guest_list_check_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.guest_list_check_label.setText("")
        self.guest_list_check_label.setObjectName("guest_list_check_label")
        self.id_input = QtWidgets.QLineEdit(self.centralwidget)
        self.id_input.setGeometry(QtCore.QRect(1, 370, 701, 31))
        self.id_input.setObjectName("id_input")
        self.count_label = QtWidgets.QLabel(self.centralwidget)
        self.count_label.setGeometry(QtCore.QRect(20, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.count_label.setFont(font)
        self.count_label.setObjectName("count_label")
        self.list_preview = QtWidgets.QListWidget(self.centralwidget)
        self.list_preview.setGeometry(QtCore.QRect(11, 70, 371, 201))
        self.list_preview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_preview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.list_preview.setObjectName("list_preview")
        self.graph_widget = QtWidgets.QWidget(self.centralwidget)
        self.graph_widget.setGeometry(QtCore.QRect(410, 70, 371, 201))
        self.graph_widget.setObjectName("graph_widget")
        self.graph_label = QtWidgets.QLabel(self.centralwidget)
        self.graph_label.setGeometry(QtCore.QRect(410, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.graph_label.setFont(font)
        self.graph_label.setObjectName("graph_label")
        sigmaSwiper.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(sigmaSwiper)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(64, 64))
        self.toolBar.setObjectName("toolBar")
        sigmaSwiper.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_load_guest_list = QtWidgets.QAction(QIcon('icons/folder-1.png'),'Open Guest List',sigmaSwiper)
        self.action_export_list = QtWidgets.QAction(QIcon('icons/technology-1.png'),'Save Attendance',sigmaSwiper)
        self.action_exit = QtWidgets.QAction(QIcon('icons/arrow-1.png'),'Exit',sigmaSwiper)
        self.toolBar.setStyleSheet('QToolBar{spacing:275px;}')
        self.toolBar.addAction(self.action_load_guest_list)
        self.toolBar.addAction(self.action_export_list)
        self.toolBar.addAction(self.action_exit)
        self.setTabOrder(self.id_input, self.submit_button)
        #sigmaSwiper.showFullScreen()
        self.retranslateUi(sigmaSwiper)
        QtCore.QMetaObject.connectSlotsByName(sigmaSwiper)

    def retranslateUi(self, sigmaSwiper):
        _translate = QtCore.QCoreApplication.translate
        sigmaSwiper.setWindowTitle(_translate("sigmaSwiper", "Sigma Swiper"))
        self.guest_list_label.setText(_translate("sigmaSwiper", "Status:"))
        self.submit_button.setText(_translate("sigmaSwiper", "Submit"))
        self.count_label.setText(_translate("sigmaSwiper", "Number Of Guests:"))
        self.graph_label.setText(_translate("sigmaSwiper", "Pulse:"))
        self.toolBar.setWindowTitle(_translate("sigmaSwiper", "toolBar"))
        self.action_load_guest_list.setText(_translate("sigmaSwiper", "Load Guest List..."))
        self.action_export_list.setText(_translate("sigmaSwiper", "Save Attendance List..."))
        self.action_exit.setText(_translate("sigmaSwiper", "Exit"))

